### ISSUE TITLE
Doesnt build with standard Android Studio setup

### ISSUE THREAD

**Issue by RichyHBM** [zacharee/WidgetDrawer#1]
I tried to compile and build on android studio, as well as gradle, and after removing fabric and google services there are compile errors in DrawerHost.

These are:
`e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (6, 20): Unresolved reference: WindowConfiguration
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (49, 5): Too many arguments for public constructor AppWidgetHost(p0: Context!, p1: Int) defined in android.appwidget.AppWidgetHost
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (49, 21): Unresolved reference: OnClickHandler
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (51, 21): Unresolved reference: OnClickHandler
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (52, 29): Unresolved reference: OnClickHandler
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (54, 22): Unresolved reference: OnClickHandler
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (56, 5): Too many arguments for public constructor AppWidgetHost(p0: Context!, p1: Int) defined in android.appwidget.AppWidgetHost
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (66, 76): Unresolved reference: OnClickHandler
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (69, 9): 'onClickHandler' overrides nothing
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (76, 76): Unresolved reference: WindowConfiguration
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (77, 42): Unresolved reference: StackId
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (79, 35): Unresolved reference: isActivity
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (83, 23): Unresolved reference: onClickHandler
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (87, 9): 'onClickHandler' overrides nothing
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (93, 31): Unresolved reference: isActivity
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (97, 26): Unresolved reference: onClickHandler
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (100, 9): 'setEnterAnimationId' overrides nothing
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (119, 20): Unresolved reference: isActivity
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/views/Drawer.kt: (444, 5): 'onActivityResult' overrides nothing`

**Comment by zacharee** [comment]
I had to use some hidden APIs for the current features. You'll need to replace the android-28 JAR with [this one](https://github.com/anggrayudi/android-hidden-api/issues/46#issuecomment-449929036).

**Comment by RichyHBM** [comment]
That seems to have fixed a bunch of the issues, however still seem to get errors about accessing private methods

`e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (46, 67): Cannot access '<init>': it is private in 'AppWidgetHost'
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (66, 64): Cannot access '<init>': it is private in 'OnClickHandler'
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (69, 9): 'public open fun onClickHandler(view: View, pendingIntent: PendingIntent, fillInIntent: Intent): Boolean defined in tk.zwander.widgetdrawer.misc.DrawerHost.InnerOnClickHandlerPie' has no access to 'private open fun onClickHandler(p0: View!, p1: PendingIntent!, p2: Intent!): Boolean defined in android.widget.RemoteViews.OnClickHandler', so it cannot override it
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (79, 35): Function invocation 'isActivity()' expected
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (79, 35): Cannot access 'isActivity': it is private in 'PendingIntent'
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (83, 23): Cannot access 'onClickHandler': it is private in 'OnClickHandler'
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (93, 31): Function invocation 'isActivity()' expected
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (93, 31): Cannot access 'isActivity': it is private in 'PendingIntent'
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (119, 20): Function invocation 'isActivity()' expected
e: /home/richy/Desktop/WidgetDrawer/app/src/main/java/tk/zwander/widgetdrawer/misc/DrawerHost.kt: (119, 20): Cannot access 'isActivity': it is private in 'PendingIntent'
`

**Comment by zacharee** [comment]
Strange.. those methods aren't private. Are you using AS 3.5?

Sent from Nine
________________________________

**Comment by RichyHBM** [comment]
I'm just building from gradle

**Comment by zacharee** [comment]
You aren't using Android Studio?

**Comment by RichyHBM** [comment]
Managed to get it working, turns out I needed to use that exact jar, and not the latest api28 on the hidden api repo
